AlphaHotel/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AlphaHotel.Areas.Admin.Models;
using AlphaHotel.Infrastructure.MappingProviders;
using AlphaHotel.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AlphaHotel.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrator")]
    [Route("[area]/[controller]/[action]")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;
        private readonly IMappingProvider mapper;

        public CategoryController(ICategoryService categoryService, IMappingProvider mapper)
        {
            this.categoryService = categoryService ?? throw new ArgumentNullException(nameof(categoryService));
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        [HttpGet]
        public async Task<IActionResult> CreateCategory()
        {
            var categories = await this.categoryService.ListAllCategoriesAsync();
            var vm = this.mapper.MapTo<CreateCategoryViewModel>(categories);

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCategory(CreateCategoryViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return BadRequest("Invalid parameters!");
            }

            await this.categoryService.AddCategory(model.CategoryName);
            return Json(model);
        }
    }
}

AlphaHotel/Controllers/BusinessController.cs
using System;
using System.Threading.Tasks;
using AlphaHotel.Models;
using AlphaHotel.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace AlphaHotel.Controllers
{
    public class BusinessController : Controller
    {
        private const int pageSize = 9;
        private const int feedbacksCount = 4;
        private readonly IBusinessService businessService;
        private readonly IFeedbackService feedbackService;
        private readonly ILogger<BusinessController> logger;

        public BusinessController(IBusinessService businessService, IFeedbackService feedbackService, ILogger<BusinessController> logger)
        {
            this.businessService = businessService ?? throw new ArgumentNullException(nameof(businessService));
            this.feedbackService = feedbackService ?? throw new ArgumentNullException(nameof(feedbackService));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public async Task<IActionResult> Details(int id)
        {
            var vm = await this.businessService.FindDetaliedBusinessAsync(id, feedbacksCount);
            //var log = this.logger.LogInformation("BusinessController");
            logger.LogWarning("Proba", "neshot stana");
            return View(vm);
        }

        public async Task<IActionResult> ShowAllBusinesses(int? pageNumber)
        {
            var vm = await this.businessService.ListAllBusinessesByPageAsync(pageNumber, pageSize);

            return View(vm);
        }

        public async Task<IActionResult> FindBusiness([FromQuery(Name = "keyword")] string keyword)
        {
            var businesses = await this.businessService.ListAllBusinessesContainsKeyWordAsync(keyword ?? "".ToLower());

            return Json(businesses);
        }

        [HttpPost]
        public async Task<IActionResult> SendFeedback(SendFeedbackViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                //var log = this.logger.CreateLogger("BusinessController");
                //log.LogInformation("Error", "Test");
                return BadRequest("Invalid parameters");
            }

            await this.feedbackService.AddFeedbackAsync(model.FeedbackText, model.Rating, model.Author, model.BusinessId);
            return Json(model);
        }
    }
}

AlphaHotel/Controllers/FeedbackController.cs
using System;
using System.Threading.Tasks;
using AlphaHotel.Services.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace AlphaHotel.Controllers
{
    public class FeedbackController : Controller
    {
        private const int pageSize = 5;
        private readonly IFeedbackService feedbackService;

        public FeedbackController(IFeedbackService feedbackService)
        {
            this.feedbackService = feedbackService ?? throw new ArgumentNullException(nameof(feedbackService));
        }

        public async Task<IActionResult> ListAllFeedbacksForScroll(int businessId, int? pageNumber)
        {
            var feedbacks = await this.feedbackService.ListAllFeedbacksForUserAsync(businessId, pageNumber, pageSize);

            return PartialView("_AllFeedbacks", feedbacks);
        }

        public async Task<IActionResult> ListAdditionalFeedbacksForScroll(int businessId, int? pageNumber)
        {
            var feedbacks = await this.feedbackService.ListAllFeedbacksForUserAsync(businessId, pageNumber, pageSize);

            return PartialView("_AdditionalFeedbacks", feedbacks);
        }
    }
}

AlphaHotel/Views/Shared/_AddLogPartial.cshtml
@model AddLogViewModel

<link rel="stylesheet" href="~/css/modal-button.css">

<button type="button" class="btn btn-primary fab" data-toggle="modal" data-target="#exampleModal" id="add-log-btn"> + </button>
<div class="modal fade centered-modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="add-log-content">

            <div class="modal-header" id="add-log-header">
                <h3 class="modal-title" id="exampleModalLabel">Add New Log</h3>
                <button type="button" id="close-add-log-btn" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <form asp-area="Manager" asp-controller="LogBook" asp-action="AddLog" id="add-log-form" enctype="multipart/form-data">
                    <div id="dropdown-partial" class="form-group">

                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.Description" class="col-form-label">Log Description:</label>
                        <textarea asp-for="@Model.Description" rows="3" class="form-control" id="log-description"></textarea>
                        <span asp-validation-for="@Model.Description" class="text-danger"></span>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-warning btn-lg">Submit</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

@section scripts {
    <partial name="_validationscriptspartial" />
}

AlphaHotel/Views/Shared/_AdditionalFeedbacks.cshtml
@model IPaginatedList<FeedbackDTO>

@foreach (var feedback in Model.Items)
{
    <div class="media testimonial_item">
        <div class="media-body">
            <h4>@feedback.Text</h4>
            <p>@feedback.Author, Reviewed: @feedback.CreatedOn.ToString("dd MMM yyyy, HH:mm")</p>
            <div class="star">
                @for (int i = 0; i < feedback.Rate; i++)
                {
                    <a><i class="fa fa-star"></i></a>
                }

                @for (int i = feedback.Rate; i < 5; i++)
                {
                    <a><i class="fa fa-star-o"></i></a>
                }
            </div>
        </div>
    </div>
    <hr />
}

AlphaHotel/Views/Shared/_AllFeedbacks.cshtml
@model IPaginatedList<FeedbackDTO>

<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" id="show-feedback-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="modal-header">
                <h5 class="modal-title" id="feedback-title">Feedbacks</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="show-feedback-body">
                @foreach (var feedback in Model.Items)
                {
                    <div class="media testimonial_item">
                        <div class="media-body">
                            <h4>@feedback.Text</h4>
                            <p>@feedback.Author, Reviewed: @feedback.CreatedOn.ToString("dd MMM yyyy, HH:mm")</p>
                            <div class="star">
                                @for (int i = 0; i < feedback.Rate; i++)
                                {
                                    <a><i class="fa fa-star"></i></a>
                                }

                                @for (int i = feedback.Rate; i < 5; i++)
                                {
                                    <a><i class="fa fa-star-o"></i></a>
                                }
                            </div>
                        </div>
                    </div>
                    <hr />
                }
            </div>
        </div>
    </div>
</div>

AlphaHotel/Views/Shared/_DropdownPartial.cshtml
@model LogBooksCategoriesDTO

@foreach (var logbook in Model.LogBooks)
{
    <div class="status-div">
        <select class="status-dropdown nice-select">
            <option value=@logbook.Id>@logbook.Name</option>
        </select>
    </div>
}

@foreach (var category in Model.Categories)
{
    <div class="status-div">
        <select class="status-dropdown nice-select">    
            <option value=@category.Name>@category.Name</option>
        </select>
    </div>
}

@*<div class="dropdown nice-select">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Choose LogBook
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            @foreach (var logbook in Model.LogBooks)
            {
                <a class="dropdown-item" href="#">@logbook.Name</a>
            }
        </div>
    </div>
    <div class="dropdown nice-select">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Choose Category
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            @foreach (var category in Model.Categories)
            {
                <a class="dropdown-item" href="#">@category.Name</a>
            }
        </div>
    </div>*@



@*<div class="col-lg-4 form-group">
        <label class="text-black-50">Choose sensor type</label>
        <select asp-for="@Model.MeasureTypeId" asp-items="Model.MeasureTypes" class="form-control text-warning text-monospace">
            <option value="all" class="grey_color">-- All --</option>
        </select>

    </div>*@

AlphaHotel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="~/images/favicon.png" type="image/png">

    <title>@ViewData["Title"] - Alpha Hotel</title>

    @*<environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        </environment>*@

    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/vendors/linericon/style.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/vendors/bootstrap-datepicker/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="~/vendors/nice-select/css/nice-select.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <!-- main css -->
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/responsive.css">
    <link rel="stylesheet" href="~/css/animate.min.css" />
</head>
<body>
    <header class="header_area">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
                <!-- Brand and toggle get grouped for better mobile display -->
                <a asp-controller="Home" asp-action="Index" class="navbar-brand logo_h"><img src="~/images/Logo.png" alt="logo"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto">
                        <li class="nav-item"><a asp-controller="Home" asp-action="Index" class="nav-link">Home</a></li>
                        <li class="nav-item"><a asp-controller="Business" asp-action="ShowAllBusinesses" class="nav-link">All hotels</a></li>
                        <li class="nav-item"><a class="nav-link" href="about.html">About us</a></li>
                        <li class="nav-item"><a class="nav-link" href="gallery.html">Gallery</a></li>
                        <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>
                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item submenu dropdown">
                                <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administrator</a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item"><a asp-area="Identity" asp-controller="Account" asp-action="Register" class="nav-link">Create Account</a></li>
                                    <li class="nav-item"><a asp-area="Admin" asp-controller="Business" asp-action="CreateBusiness" class="nav-link">Create Business</a></li>
                                    <li class="nav-item"><a asp-area="Admin" asp-controller="Account" asp-action="AllAcounts" class="nav-link">All Accounts</a></li>
                                    <li class="nav-item"><a asp-area="Admin" asp-controller="Business" asp-action="CreateLogBook" class="nav-link">Create LogBook</a></li>
                                    <li class="nav-item"><a asp-area="Admin" asp-controller="Category" asp-action="CreateCategory" class="nav-link">Create Category</a></li>
                                </ul>
                            </li>
                        }
                        @if (User.IsInRole("Manager"))
                        {
                            <li class="nav-item"><a asp-area="Manager" asp-controller="LogBook" asp-action="AllLogbookLogs" class="nav-link">My LogBooks</a></li>

                        }
                        @if (User.IsInRole("Moderator"))
                        {
                            <li class="nav-item"><a asp-area="Moderator" asp-controller="Feedback" asp-action="ListAllFeedbacks" class="nav-link">All Feedbacks</a></li>
                        }
                        <li class="nav-item">
                            <partial name="_LoginPartial" />
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    @RenderBody()

    <footer class="footer-area">
        <div class="container">
            <div class="row footer-bottom d-flex justify-content-between align-items-center">
                <p class="col-lg-8 col-sm-12 footer-text m-0">
                    Copyright &copy; 2019 Movie Catalog All Rights Reserved.
                    Designed by Alpha Team.
                </p>
                <div class="col-lg-4 col-sm-12 footer-social">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-dribbble"></i></a>
                    <a href="#"><i class="fa fa-behance"></i></a>
                </div>
            </div>
        </div>
    </footer>
    @if (User.IsInRole("Manager"))
    {
        <partial name="_AddLogPartial" model="new AddLogViewModel()" />
    }

    <partial name="_LoginAndRegisterPopup" model="new LoginViewModel()" />

    @*<environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            @*<script src="~/js/site.min.js" asp-append-version="true"></script>*@
    @*</environment>*@

    <script src="~/js/jquery-3.2.1.min.js"></script>
    <script src="~/js/popper.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/vendors/owl-carousel/owl.carousel.min.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"
            asp-fallback-src="~/js/sweet-alert.js"></script>
    <script src="~/vendors/bootstrap-datepicker/bootstrap-datetimepicker.min.js"></script>
    <script src="~/vendors/nice-select/js/jquery.nice-select.js"></script>
    <script src="~/js/stellar.js"></script>
    <script src="~/vendors/lightbox/simpleLightbox.min.js"></script>
    <script src="~/js/custom.js"></script>
    <script src="~/js/send-feedback.js"></script>
    <script src="~/js/signalr.min.js"></script>
    <script src="~/js/signalr-notifications.js"></script>
    <script src="~/js/add-log.js"></script>
    <script src="~/js/search-hotel-redirect.js"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>

AlphaHotel/Views/Shared/_LoginAndRegisterPopup.cshtml
@model LoginViewModel

<div id="login-register-popup" class="small-dialog zoom-anim-dialog mfp-hide">

    <div class="signin-wrapper">
        <div class="small-dialog-headline">
            <h4 class="text-center">Sign in</h4>
        </div>
        <div class="small-dialog-content">
            <form asp-area="Identity" asp-controller="Account" asp-action="Login" id="cariera_login" method="post">
                <p class="status"></p>
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserName"></label>
                    <input asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="checkbox pad-bottom-10">
                        <label asp-for="RememberMe">
                            <input asp-for="RememberMe" />
                            @Html.DisplayNameFor(m => m.RememberMe)
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    <input type="submit" value="Sign in" class="btn btn-main btn-effect nomargin" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

AlphaHotel/Views/Shared/_SendFeedbackPopup.cshtml
@model SendFeedbackViewModel

<link rel="stylesheet" href="~/css/star-rating.css">
<link rel="stylesheet" href="~/css/modal-button.css">

<button type="button" class="btn btn-primary fab" data-toggle="modal" data-target="#exampleModal"> + </button>

<div class="modal fade centered-modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New comment</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <form asp-controller="business" asp-action="sendfeedback" id="send-feedback-form">
                    <div class="row">
                        <div style="margin-bottom: -1px" class="col-sm-12 form-group">
                            <label>How do you rate your overall experience?</label>
                            <p>
                                <fieldset style="margin-top: -11px" class="rating">
                                    <input asp-for="@Model.Rating" type="radio" id="star5" value="5" /><label class="full" for="star5" title="Amazing - 5 stars"></label>
                                    <input asp-for="@Model.Rating" type="radio" id="star4" value="4" /><label class="full" for="star4" title="Pretty good - 4 stars"></label>
                                    <input asp-for="@Model.Rating" type="radio" id="star3" value="3" /><label class="full" for="star3" title="Okay - 3 stars"></label>
                                    <input asp-for="@Model.Rating" type="radio" id="star2" value="2" /><label class="full" for="star2" title="Bad - 2 stars"></label>
                                    <input asp-for="@Model.Rating" type="radio" id="star1" value="1" /><label class="full" for="star1" title="Appaling - 1 star"></label>
                                </fieldset>
                            </p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.Author" class="col-form-label">Guest's Name:</label>
                        <input asp-for="@Model.Author" class="form-control" id="guest-name" placeholder="Name is optional" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Name is optional'">
                        <span asp-validation-for="@Model.Author" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.FeedbackText" class="col-form-label">Feedback:</label>
                        <textarea asp-for="@Model.FeedbackText" rows="3" class="form-control" id="feedback-text"></textarea>
                        <span asp-validation-for="@Model.FeedbackText" class="text-danger"></span>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>


        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/send-feedback.js"></script>
}